package com.jerryhumor.news.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setSource(java.lang.Integer source) {
		set("source", source);
		return (M)this;
	}

	public java.lang.Integer getSource() {
		return getInt("source");
	}

	public M setCategory(java.lang.Integer category) {
		set("category", category);
		return (M)this;
	}

	public java.lang.Integer getCategory() {
		return getInt("category");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}

	public java.lang.String getImg() {
		return getStr("img");
	}

	public M setNewsTime(java.util.Date newsTime) {
		set("news_time", newsTime);
		return (M)this;
	}

	public java.util.Date getNewsTime() {
		return get("news_time");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setNewsId(java.lang.String newsId) {
		set("news_id", newsId);
		return (M)this;
	}

	public java.lang.String getNewsId() {
		return getStr("news_id");
	}

	public M setFkArticleId(java.lang.Integer fkArticleId) {
		set("fk_article_id", fkArticleId);
		return (M)this;
	}

	public java.lang.Integer getFkArticleId() {
		return getInt("fk_article_id");
	}

}
